namespace: challenge1
image:
  repository: touching/masterclass-fastapi-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  port: 8000

env:
  mode: "production"
  # INSECURE: appToken is passed as a plaintext env var.
  # Replace this with a volume-mounted Secret.
  # Hint: kubectl get secrets -n challenge1
  # The secret key "legacy-sys-token" should be mapped to filename "credentials.key"
  appToken: ""
