#!/bin/bash
echo "Setting up the environment..."
while [ ! -f /tmp/setup-finished ]; do
  sleep 2
  echo -n "."
done

echo ""

echo ""
echo "# 🎄 The Impatient Elf - Challenge: Put the Elf Back in Line"
echo ""
echo "🔴 Intermediate • ~25 min • initContainers, Pod Startup Ordering, CrashLoopBackOff"
echo ""
echo "The rogue elves moved the catalog-restocking elf out of the prep shift. The shop opens before the shelves are stocked and crash-loops."
echo ""
echo "## Your Task"
echo ""
echo "Fix the `gift-registry` Deployment in namespace `workshop` so the elf's catalog rebuild is guaranteed to **exit successfully before the shop container starts**."
echo ""
echo "### Requirements"
echo ""
echo "- The elf's work (migrate + restock) must run to completion **first** — not in parallel with the shop."
echo "- The shop container must only start once that work has **exited with code 0**."
echo "- `wait-for-db` must keep doing its job."
echo "- Don't cheat by removing the elf — the shelves still have to be restocked."
echo ""
echo "Apply your change to the **Deployment** (not a temporary Pod), then wait a moment for a fresh Pod to boot. You'll know it's fixed when:"
echo ""
echo "```bash"
echo "kubectl -n workshop get pods -l app=gift-registry"
echo "# NAME                           READY   STATUS    RESTARTS"
echo "# gift-registry-...              1/1     Running   0"
echo ""
echo "kubectl -n workshop exec deploy/gift-registry -- \"\\"
echo "  python -c 'import urllib.request; print(urllib.request.urlopen(\"http://127.0.0.1:8000/healthz\").read())'\""
echo "# {\"status\": \"ok\", \"catalog_rows\": 15000}"
echo "```\n"
echo ""
echo "## How to Fix"
echo ""
echo "Move the `elf` container from `containers:` to `initContainers:` (after `wait-for-db`). The guaranteed start order becomes:"
echo ""
echo "```"
echo "wait-for-db (init) → elf: migrate + restock, exit 0 (init) → gift-registry"
echo "```\n"
echo ""
echo "## Useful Commands"
echo ""
echo "- View the broken Deployment: `kubectl -n workshop get deployment gift-registry -o yaml`{{exec interrupt}}\n"
echo "- Edit `~/app.yaml` to move the elf container to initContainers:"
echo "  - Remove the elf from `containers:`"
echo "  - Add the elf to `initContainers:` as an init container"
echo ""
echo "1. Edit `~/app.yaml` so the elf's work finishes before the shop container starts."
echo "2. Redeploy: `kubectl apply -f ~/app.yaml`{{exec interrupt}}\n"
echo "3. Watch a fresh Pod come up healthy: `kubectl -n workshop get pods -w`{{exec interrupt}}\n"
echo "4. Click the `Check` button!"
echo ""
echo "✅ You can now begin!"
