namespace: challenge1
image:
  repository: touching/masterclass-fastapi-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  port: 8000

#---Edit the lines below here for the challenge---
env:
  mode: "production"
  appToken: "myverysecretpassword"
