apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: backend-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "myregistry.io/app-image:latest" 
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
