apiVersion: apps/v1
kind: Deployment
metadata:
  name: gift-database-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gift-database-client
  template:
    metadata:
      labels:
        app: gift-database-client
    spec:
      containers:
        - name: db-client
          image: busybox:1.36
          command: ["sh", "-c", "echo \"Connecting to database with password: $DB_PASSWORD\" && sleep 3600"]
          ports:
            - containerPort: 5432
          env:
            - name: DB_HOST
              value: "northpole-db.svc.cluster.local"
            - name: DB_USER
              value: "santa"
            - name: DB_PASSWORD
              value: "NorthPole2025!"
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
