apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleigh-telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleigh-telemetry
  template:
    metadata:
      labels:
        app: sleigh-telemetry
        ## Step 3
        app.kubernetes.io/name: "gift-tracking-app"
        app.kubernetes.io/instance: "gift-tracking-app"
    spec:
      ## Step 4
      serviceAccountName: gift-tracking-sa
      ## Step 4 Bonus
      automountServiceAccountToken: false
      containers:
        - name: sleigh-telemetry
          image: localhost:30500/sleigh-telemetry:latest
          ports:
            - containerPort: 8000
          ##Step 1
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ## Step 2
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
