# Default values for app-chart.
# This is a barebones values file.
# Note that some configurations are missing or hardcoded in the templates.

replicaCount: 1

image:
  repository: touching/masterclass-fastapi-app
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

securityContext:
  enabled: true
  runAsNonRoot: true
  capabilities:
    drop:
      - "ALL"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
