apiVersion: v1
kind: ServiceAccount
metadata:
  name: gift-tracking-sa
  namespace: gift-tracking
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gift-tracking-skeleton-key
subjects:
  - kind: ServiceAccount
    name: gift-tracking-sa
    namespace: gift-tracking
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
