apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "masterclass-fastapi-app.fullname" . }}
  labels:
    {{- include "masterclass-fastapi-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "masterclass-fastapi-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "masterclass-fastapi-app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: MODE
              value: {{ .Values.env.mode }}
            - name: APP_TOKEN
              value: {{ .Values.env.appToken }}
