---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodb
spec:
  serviceName: "mongodb-service"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/name: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/name: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:8.2.6
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongodb-secret
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 5Gi
